
package com.meme.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldWS", targetNamespace = "http://webservice.meme.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.meme.webservice.UserDetails
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.meme.com/HelloWorldWS/getUserDetailsRequest", output = "http://webservice.meme.com/HelloWorldWS/getUserDetailsResponse")
    public UserDetails getUserDetails(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.meme.com/HelloWorldWS/getHelloWorldRequest", output = "http://webservice.meme.com/HelloWorldWS/getHelloWorldResponse")
    public String getHelloWorld();

}
